services:
  neuroblogger:
    restart: always
    build:
      context: .
    ports:
      - "80:80"
    env_file:
      - .env
    environment:
      - NODE_ENV=production
    volumes:
      - ./src:/app/src
    command: ["npm", "start"]