version: '3.8'
services:
  web:
    build:
      context: ./
      target: runner
    volumes:
      - .:/app
    command: npm run dev
    ports:
      - "80:80"
    environment:
      NODE_ENV: production


# https://geshan.com.np/blog/2023/01/nextjs-docker/