[phases.setup]
nixPkgs = ["nodejs-20_x", "pnpm"]

[phases.install]
cmds = ["pnpm install --frozen-lockfile"]

[phases.build]
cmds = ["pnpm run build"]

[start]
cmd = "pnpm run start"

[variables]
NODE_ENV = "production"
NEXT_PUBLIC_LOCAL_URL = "https://999-web-production.up.railway.app"
NEXT_PUBLIC_SITE_URL = "https://dao999nft.com"
NEXT_PUBLIC_DEV = "false"
