import Image from 'next/image'
import { faker } from '@faker-js/faker'
const w = 200
const h = 200

export const data = [
  <Image
    key='github-actions'
    src={faker.image.personPortrait()}
    width={w}
    height={h}
    alt='GitHub Actions'
    className='rounded-full'
  />,
  <Image
    key='git-icon'
    src={faker.image.personPortrait()}
    width={w}
    height={h}
    alt='Git Icon'
    className='rounded-full'
  />,
  <Image
    key='kotlin'
    src={faker.image.personPortrait()}
    width={w}
    height={h}
    alt='Kotlin'
    className='rounded-full'
  />,
  <Image
    key='android-icon'
    src={faker.image.personPortrait()}
    width={w}
    height={h}
    alt='Android Icon'
    className='rounded-full'
  />,
  <Image
    key='nextjs-icon'
    src={faker.image.personPortrait()}
    width={w}
    height={h}
    alt='Next.js Icon'
    className='rounded-full'
  />,
  <Image
    key='nodejs-icon'
    src={faker.image.personPortrait()}
    width={w}
    height={h}
    alt='Node.js Icon'
    className='rounded-full'
  />,
  <Image
    key='html-5'
    src={faker.image.personPortrait()}
    width={w}
    height={h}
    alt='HTML5'
    className='rounded-full'
  />,
  <Image
    key='javascript'
    draggable='false'
    src={faker.image.personPortrait()}
    width={w}
    height={h}
    alt='JavaScript'
    className='rounded-full'
  />,
  <Image
    key='css-3'
    src={faker.image.personPortrait()}
    width={w}
    height={h}
    alt='CSS3'
    className='rounded-full'
  />,
  <Image
    key='unity'
    src={faker.image.personPortrait()}
    width={w}
    height={h}
    alt='Unity'
    className='rounded-full'
  />,
  <Image
    key='microsoft-windows'
    src={faker.image.personPortrait()}
    width={w}
    height={h}
    alt='Microsoft Windows'
    className='rounded-full'
  />,
  <Image
    key='fedora'
    src={faker.image.personPortrait()}
    width={w}
    height={h}
    alt='Fedora'
    className='rounded-full'
  />,
  <Image
    key='suse'
    src={faker.image.personPortrait()}
    width={w}
    height={h}
    alt='SUSE'
    className='rounded-full'
  />,
  <Image
    key='jest'
    src={faker.image.personPortrait()}
    width={w}
    height={h}
    alt='Jest'
    className='rounded-full'
  />,
  <Image
    key='ubuntu'
    src={faker.image.personPortrait()}
    width={w}
    height={h}
    alt='Ubuntu'
    className='rounded-full'
  />,
  <Image
    key='react'
    src={faker.image.personPortrait()}
    width={w}
    height={h}
    alt='React'
    className='rounded-full'
  />,
  <Image
    key='docker-icon'
    src={faker.image.personPortrait()}
    width={w}
    height={h}
    alt='Docker Icon'
    className='rounded-full'
  />,
  <Image
    key='rust'
    src={faker.image.personPortrait()}
    width={w}
    height={h}
    alt='Rust'
    className='rounded-full'
  />,
  <Image
    key='c'
    src={faker.image.personPortrait()}
    width={w}
    height={h}
    alt='C'
    className='rounded-full'
  />,
  <Image
    key='c-sharp'
    src={faker.image.personPortrait()}
    width={w}
    height={h}
    alt='C Sharp'
    className='rounded-full'
  />,
  <Image
    key='java'
    src={faker.image.personPortrait()}
    width={w}
    height={h}
    alt='Java'
    className='rounded-full'
  />,
  <Image
    key='firebase'
    src={faker.image.personPortrait()}
    width={w}
    height={h}
    alt='Firebase'
    className='rounded-full'
  />,
  <Image
    key='youtrack'
    src={faker.image.personPortrait()}
    width={w}
    height={h}
    alt='YouTrack'
    className='rounded-full'
  />,
  <Image
    key='figma'
    src={faker.image.personPortrait()}
    width={w}
    height={h}
    alt='Figma'
    className='rounded-full'
  />,
]
